FROM maven:3.6.0-jdk-8-slim
LABEL maintainer "Yasumasa Suenaga <yasuenag@gmail.com>"

RUN apt-get update && apt-get upgrade -y \
  && apt-get install -y openjfx wget bzip2 \
  && apt-get clean
COPY common/setup.sh common/maven-proxy.sh archives/build.sh ./

CMD ["./build.sh"]
