FROM maven:3.6-jdk-13
LABEL maintainer "Yasumasa Suenaga <yasuenag@gmail.com>"

RUN  yum update -y && yum install -y wget bzip2 && yum clean all
COPY common/setup.sh common/maven-proxy.sh archives/build.sh ./

CMD ["./build.sh"]
