kind: PersistentVolume
apiVersion: v1
metadata:
  name: host-pv-maven
  labels:
    type: local
spec:
  storageClassName: heapstats-maven
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/maven-repo"
