kind: PersistentVolume
apiVersion: v1
metadata:
  name: host-pv
  labels:
    type: local
spec:
  storageClassName: heapstats
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/share"
